### ISSUE TITLE
RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [1, 1, 360, 640]

### ISSUE THREAD

**Issue by dbAIStudio** [milesial/Pytorch-UNet#129] opened 2020-02-10 07:44 UTC
I have three classes. The training mask is assigned in 0,1,2 gray scale. The training times are wrong. After reading the description of previous related problems, my problem should be that there is a problem in the training load mask. If there is more classification, do I need to modify your code?How to modify？

**Comment by dbAIStudio** [comment] 2020-02-10 07:50
![mmexport1581320848119](https://user-images.githubusercontent.com/45676311/74130275-9d768c80-4bd9-11ea-8fea-fe6b062e2aa8.jpg)
As shown in the figure, I tried to modify the way of loading mask during training, and still reported the error above

**Comment by Bienqq** [comment] 2020-02-10 17:55
Hello,

Unfortunately I've experienced related error :

`RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [1, 3, 259, 344]`

I have also 3 classes:
1 background (black)
2 cell (blue)
3. nucleus (green)

Therefore in code I have:

`net = UNet(n_channels=3, n_classes=3)
`

My input image:
![image](https://user-images.githubusercontent.com/35897213/74175773-c1b48680-4c36-11ea-9dd4-456dc0c0d2c6.png)

My mask:
![image](https://user-images.githubusercontent.com/35897213/74175760-b8c3b500-4c36-11ea-8292-4b6e3b194bd6.png)

Could You please help ?

**Comment by dbAIStudio** [comment] 2020-02-11 07:06
> Hello,
> 
> Unfortunately I've experienced related error :
> 
> `RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [1, 3, 259, 344]`
> 
> I have also 3 classes:
> 1 background (black)
> 2 cell (blue)
> 3. nucleus (green)
> 
> Therefore in code I have:
> 
> `net = UNet(n_channels=3, n_classes=3) `
> 
> My input RGB image:
> ![image](https://user-images.githubusercontent.com/35897213/74175773-c1b48680-4c36-11ea-9dd4-456dc0c0d2c6.png)
> 
> My mask:
> ![image](https://user-images.githubusercontent.com/35897213/74175760-b8c3b500-4c36-11ea-8292-4b6e3b194bd6.png)
> 
> Could You please help ?

I haven't solved it. I'm asking the author

**Comment by Bienqq** [comment] 2020-02-11 18:52
I have converted my masks to 1-channel gray-scale image with pixels values 0,1,2 just like You.
Also I have added following line in train.py
`true_masks = true_masks[0]`
before line 78 and also in eval.py before line 21
I started training successfully but I cannot change batch_size to other value than 1
Otherwise I got following error:

> Traceback (most recent call last):
  File "E:/Magisterka/Programy/unet-segmentation/Pytorch-UNet/train.py", line 181, in <module>
    val_percent=args.val / 100)
  File "E:/Magisterka/Programy/unet-segmentation/Pytorch-UNet/train.py", line 66, in train_net
    for batch in train_loader:
  File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "C:\Program Files\Python36\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\_utils\collate.py", line 75, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\_utils\collate.py", line 75, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\_utils\collate.py", line 56, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: Expected object of scalar type Double but got scalar type Byte for sequence element 1 in sequence argument at position #1 'tensors'


Process finished with exit code 1

**Comment by tim-vdl** [comment] 2020-02-14 10:18
Hey, checkout issue #123 were the same problem is discussed. I suggest a solution that worked for me.

**Comment by tim-vdl** [comment] 2020-02-14 10:29
Duplicate of #123

**Comment by ljw919** [comment] 2020-02-19 16:08
when u use crossentroyloss,u need to cut one dimension of the label before throw it into the loss_func.

**Comment by picEmily** [comment] 2020-04-22 08:50
how do you deal it？ @dbAIStudio 
I have three classes. The training mask is assigned in 0,1,2 gray scale. The training image is gray-scale image。
 I got following error：
RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [1, 1, 576, 448]

**Comment by anup1986** [comment] 2020-05-11 15:27
How did you solved this

**Comment by milesial** [comment] 2020-07-28 22:36
Duplicate of #123

**Closed by milesial** 2020-07-28 22:36 UTC

**Comment by luka0714** [comment] 2020-11-02 08:38
please

**Comment by petervlad** [comment] 2021-01-24 10:44
> I have converted my masks to 1-channel gray-scale image with pixels values 0,1,2 just like You.
> Also I have added following line in train.py
> `true_masks = true_masks[0]`
> before line 78 and also in eval.py before line 21
> I started training successfully but I cannot change batch_size to other value than 1
> Otherwise I got following error:
> 
> > Traceback (most recent call last):
> > File "E:/Magisterka/Programy/unet-segmentation/Pytorch-UNet/train.py", line 181, in 
> > val_percent=args.val / 100)
> > File "E:/Magisterka/Programy/unet-segmentation/Pytorch-UNet/train.py", line 66, in train_net
> > for batch in train_loader:
> > File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 819, in **next**
> > return self._process_data(data)
> > File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
> > data.reraise()
> > File "C:\Program Files\Python36\lib\site-packages\torch_utils.py", line 369, in reraise
> > raise self.exc_type(msg)
> > RuntimeError: Caught RuntimeError in DataLoader worker process 0.
> > Original Traceback (most recent call last):
> > File "C:\Program Files\Python36\lib\site-packages\torch\utils\data_utils\worker.py", line 178, in _worker_loop
> > data = fetcher.fetch(index)
> > File "C:\Program Files\Python36\lib\site-packages\torch\utils\data_utils\fetch.py", line 47, in fetch
> > return self.collate_fn(data)
> > File "C:\Program Files\Python36\lib\site-packages\torch\utils\data_utils\collate.py", line 75, in default_collate
> > return {key: default_collate([d[key] for d in batch]) for key in elem}
> > File "C:\Program Files\Python36\lib\site-packages\torch\utils\data_utils\collate.py", line 75, in 
> > return {key: default_collate([d[key] for d in batch]) for key in elem}
> > File "C:\Program Files\Python36\lib\site-packages\torch\utils\data_utils\collate.py", line 56, in default_collate
> > return torch.stack(batch, 0, out=out)
> > RuntimeError: Expected object of scalar type Double but got scalar type Byte for sequence element 1 in sequence argument at position #1 'tensors'
> 
> Process finished with exit code 1



> I have converted my masks to 1-channel gray-scale image with pixels values 0,1,2 just like You.
> Also I have added following line in train.py
> `true_masks = true_masks[0]`
> before line 78 and also in eval.py before line 21
> I started training successfully but I cannot change batch_size to other value than 1
> Otherwise I got following error:
> 
> > Traceback (most recent call last):
> > File "E:/Magisterka/Programy/unet-segmentation/Pytorch-UNet/train.py", line 181, in 
> > val_percent=args.val / 100)
> > File "E:/Magisterka/Programy/unet-segmentation/Pytorch-UNet/train.py", line 66, in train_net
> > for batch in train_loader:
> > File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 819, in **next**
> > return self._process_data(data)
> > File "C:\Program Files\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
> > data.reraise()
> > File "C:\Program Files\Python36\lib\site-packages\torch_utils.py", line 369, in reraise
> > raise self.exc_type(msg)
> > RuntimeError: Caught RuntimeError in DataLoader worker process 0.
> > Original Traceback (most recent call last):
> > File "C:\Program Files\Python36\lib\site-packages\torch\utils\data_utils\worker.py", line 178, in _worker_loop
> > data = fetcher.fetch(index)
> > File "C:\Program Files\Python36\lib\site-packages\torch\utils\data_utils\fetch.py", line 47, in fetch
> > return self.collate_fn(data)
> > File "C:\Program Files\Python36\lib\site-packages\torch\utils\data_utils\collate.py", line 75, in default_collate
> > return {key: default_collate([d[key] for d in batch]) for key in elem}
> > File "C:\Program Files\Python36\lib\site-packages\torch\utils\data_utils\collate.py", line 75, in 
> > return {key: default_collate([d[key] for d in batch]) for key in elem}
> > File "C:\Program Files\Python36\lib\site-packages\torch\utils\data_utils\collate.py", line 56, in default_collate
> > return torch.stack(batch, 0, out=out)
> > RuntimeError: Expected object of scalar type Double but got scalar type Byte for sequence element 1 in sequence argument at position #1 'tensors'
> 
> Process finished with exit code 1

Hi, added your line and training went fine. But now when I want to use predict.py i have these errors. I can't figure out how to modify the code in order to work. How did you solved it?
`RuntimeError: Error(s) in loading state_dict for UNet:
        size mismatch for outc.conv.weight: copying a param with shape torch.Size([2, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 64, 1, 1]).
        size mismatch for outc.conv.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([1]).
`
